## Top 8 Powerful Functions in Python for Deeper Data Analysis

1. GroupBy
2. pivot_table
3. Aggregate
4. cross_tab
5. concat
6. apply
7. lambda
8. del (Keyword)

## 1. GroupBy

In [7]:
import pandas as pd
insurance_data = pd.read_csv("Insurance.csv");
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

## 1.1 Perfom initail analysis

In [8]:
insurance_data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [9]:
insurance_data.dtypes

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
charges     float64
dtype: object

In [12]:
insurance_data.describe(include="all")

,age,sex,bmi,children,smoker,region,charges
count,1338.000000,1338,1338.000000,1338.000000,1338,1338,1338.000000
unique,NaN,2,NaN,NaN,2,4,NaN
top,NaN,male,NaN,NaN,no,southeast,NaN
freq,NaN,676,NaN,NaN,1064,364,NaN
mean,39.207025,NaN,30.663397,1.094918,NaN,NaN,13270.422265
std,14.049960,NaN,6.098187,1.205493,NaN,NaN,12110.011237
min,18.000000,NaN,15.960000,0.000000,NaN,NaN,1121.873900
25%,27.000000,NaN,26.296250,0.000000,NaN,NaN,4740.287150
50%,39.000000,NaN,30.400000,1.000000,NaN,NaN,9382.033000
75%,51.000000,NaN,34.693750,2.000000,NaN,NaN,16639.912515
max,64.000000,NaN,53.130000,5.000000,NaN,NaN,63770.428010

In [15]:
insurance_data["region"].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

## 1.2 pull up the avg insurance charge based on region

In [22]:
insurance_data.groupby(by="region")["charges"].mean().round(2).sort_values()

region
southwest    12346.94
northwest    12417.58
northeast    13406.38
southeast    14735.41
Name: charges, dtype: float64

## 1.2 pull up the avg insurance charge based on region and sex

#### Discrete and continuous data 

1. Discrete - Just Countable/Cannot be segmented
2. Continuous - Measurable/ have units/can also be segmented

In [23]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [24]:
insurance_data.groupby(by=["region", "sex"])["charges"].mean().round(2).sort_values()

region     sex
southwest  female    11274.41
northwest  male      12354.12
           female    12479.87
northeast  female    12953.20
southwest  male      13412.88
southeast  female    13499.67
northeast  male      13854.01
southeast  male      15879.62
Name: charges, dtype: float64

## 2. Pivot

In [31]:
pd.pivot_table(data = insurance_data, values="charges", index="region",columns="sex", "childrean"] ).round(2) # presentable comparing 2 category features vs 1 continuos

sex          female                                                    \
children          0         1         2         3         4         5
region
northeast   9789.82  17124.69  14523.22  13730.10  14542.42       NaN
northwest  12583.87  11118.86  13127.59  13430.71  11024.42   8965.80
southeast  14862.01   9869.91  11766.31  19722.98  18267.10   9923.89
southwest  10149.75  10841.64  16230.26   8438.74  10945.68  10023.65

sex            male
children          0         1         2         3         4         5
region
northeast  13389.64  15474.29  12317.91  14935.22  14442.28   6978.97
northwest   9812.97   9515.04  13762.55  22971.22  11508.32       NaN
southeast  13791.81  17424.65  18647.95  17101.82   8726.91  10306.99
southwest  13727.26   9971.33  18875.95  12071.59  17923.95   6864.67

## 3.Aggregate

In [32]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## 3.1 pull up the avg, min, max, sum insurance charge based on region

In [42]:
insurance_data.groupby(["region", "sex"])["charges"].agg(func = ["mean", "sum", "min", "max"])

                          mean           sum         min          max
region    sex
northeast female  12953.203151  2.085466e+06  2196.47320  58571.07448
          male    13854.005374  2.258203e+06  1694.79640  48549.17835
northwest female  12479.870397  2.046699e+06  2117.33885  55135.40209
          male    12354.119575  1.989013e+06  1621.34020  60021.39897
southeast female  13499.669243  2.362442e+06  1607.51010  63770.42801
          male    15879.617173  3.001248e+06  1121.87390  62592.87309
southwest female  11274.411264  1.826455e+06  1727.78500  48824.45000
          male    13412.883576  2.186300e+06  1241.56500  52590.82939

## 4. cross_tab

In [43]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### 4.1 How many smokers and non smokers based on region-wise

In [49]:
pd.crosstab(  index = insurance_data["region"], columns = insurance_data["smoker"], margins=True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

## 5.Concat

In [52]:
sales_data_2017 = pd.read_csv("Sales Transactions-2017.csv")
sales_data_2018 = pd.read_csv("Sales Transactions-2018.csv")
sales_data_2019 = pd.read_csv("Sales Transactions-2019.csv")

In [56]:
total_sales_data = pd.concat(objs = [sales_data_2017, sales_data_2018, sales_data_2019])

In [62]:
total_sales_data.dtypes

Date              str
Voucher           str
Party             str
Product           str
Qty               str
Rate              str
Gross             str
Disc              str
Voucher Amount    str
dtype: object

In [61]:
total_sales_data.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

### Level 4.5/5 Complexity Challange
merge

## 6.Apply

In [80]:
import pandas as pd
insurance_data = pd.read_csv("Insurance.csv")
insurance_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

### 6.1 Create a new column in the sane dataframe with the name "Eligiblity Criteria" where age is > 18, say Eligible else not

In [81]:
if insurance_data.age>18:
    print["Eligible"]
else:
    print["Not Eligible"]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [83]:
def get_age(x):
    if x > 18:
        return "Eligible"
    else:
        return "Not Eligible"

insurance_data["Eligible Criteria"] = insurance_data.age.apply(get_age)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

### 7.lambda

#### lambda fuction is ananymous fuction

In [85]:
insurance_data["Eligible Critria"] = insurance_data.age.apply(lambda x:1 if x>20 else 0)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria,Eligible Critria
0,19,female,27.900,0,yes,southwest,16884.92400,Eligible,0
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,0
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,1
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,1
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,1
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,1
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,0
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,0
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,1
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,1

### Explore list comprehension 3 examples forloop if in single line

explore lambda - map, filter, query

## 8.Delete

In [92]:
insurance_data
del insurance_data["Eligible Criteria"]
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]