# Chapter 1 : Getting & Knowing Your Data

In [147]:
import pandas as pd

order_details = pd.read_csv(filepath_or_buffer= "data.tsv.txt", sep = "\t")
# Insight and meaning full insights 
# insight means the customer already knows the data 
# meaningful insights mean I found out the information the customer did not know about the data

In [81]:
pd.read_table("data.tsv.txt")

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

# 1.1 Perform  Initial Analysis

In [ ]:
# Fucntion ()
# Attribute

In [148]:
order_details.shape

(4622, 5)

#### Terminology alert
* Rows - Observation or Record
* Columns - Features or Parameters

In [149]:
order_details.isnull().sum() #chain of commands or chain of functions

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [150]:
order_details.dtypes

order_id              int64
quantity              int64
item_name               str
choice_description      str
item_price              str
dtype: object

In [151]:
order_details.describe(include="all")

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

## 1.2 Fino Out the items sold in the restaurent

In [152]:
order_details.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [153]:
print(order_details["item_name"].unique())

<StringArray>
[         'Chips and Fresh Tomato Salsa',
                                  'Izze',
                      'Nantucket Nectar',
 'Chips and Tomatillo-Green Chili Salsa',
                          'Chicken Bowl',
                         'Side of Chips',
                         'Steak Burrito',
                      'Steak Soft Tacos',
                   'Chips and Guacamole',
                  'Chicken Crispy Tacos',
                    'Chicken Soft Tacos',
                       'Chicken Burrito',
                           'Canned Soda',
                      'Barbacoa Burrito',
                      'Carnitas Burrito',
                         'Carnitas Bowl',
                         'Bottled Water',
 'Chips and Tomatillo Green Chili Salsa',
                         'Barbacoa Bowl',
                                 'Chips',
                    'Chicken Salad Bowl',
                            'Steak Bowl',
                   'Barbacoa Soft Tacos',
                        'Veggie Burrito',
                           'Veggie Bowl',
                    'Steak Crispy Tacos',
   'Chips and Tomatillo Red Chili Salsa',
                 'Barbacoa Crispy Tacos',
                     'Veggie Salad Bowl',
    'Chips and Roasted Chili-Corn Salsa',
    'Chips and Roasted Chili Corn Salsa',
                   'Carnitas Soft Tacos',
                         'Chicken Salad',
                     'Canned Soft Drink',
                      'Steak Salad Bowl',
                     '6 Pack Soft Drink',
   'Chips and Tomatillo-Red Chili Salsa',
                                  'Bowl',
                               'Burrito',
                          'Crispy Tacos',
                 'Carnitas Crispy Tacos',
                           'Steak Salad',
     'Chips and Mild Fresh Tomato Salsa',
                     'Veggie Soft Tacos',
                   'Carnitas Salad Bowl',
                   'Barbacoa Salad Bowl',
                                 'Salad',
                   'Veggie Crispy Tacos',
                          'Veggie Salad',
                        'Carnitas Salad']
Length: 50, dtype: str

## 1.3 Give me the list of Top Selling items

In [154]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending = False).head(10)

item_name
Chicken Bowl                    761
Chicken Burrito                 591
Chips and Guacamole             506
Steak Burrito                   386
Canned Soft Drink               351
Chips                           230
Steak Bowl                      221
Bottled Water                   211
Chips and Fresh Tomato Salsa    130
Canned Soda                     126
Name: quantity, dtype: int64

## 1.4 Give me the list of Least Selling items

In [88]:
order_details.groupby("item_name")["quantity"].sum().sort_values().head()

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

# Chapter 2 Data Cleaning

In [157]:
order_details["item_price"].str.replace("$", "").astype(float)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: str

In [78]:
order_details.dtypes

order_id                int64
quantity                int64
item_name                 str
choice_description        str
item_price            float64
dtype: object

In [90]:
order_details["item_price"].str.replace("$", "").astype(float)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [91]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [92]:
order_details.dtypes

order_id              int64
quantity              int64
item_name               str
choice_description      str
item_price              str
dtype: object

In [93]:
order_details["item_price"] = order_details["item_price"].str.replace("$", "").astype(float)

In [95]:
order_details
order_details.dtypes

order_id                int64
quantity                int64
item_name                 str
choice_description        str
item_price            float64
dtype: object

In [97]:
order_details.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

## Task 
1. Find out the Top 5 selling items that individuals' revenue made
2. Total Revenue of top 5 items sold

In [130]:
order_details["revenue"] = order_details["quantity"] * order_details["item_price"]
print(pd.DataFrame(data = order_details.revenue))

order_details
order_details.groupby("item_name")["revenue"].sum().sort_values(ascending = False).head()

#order_details.groupby(by="item_name").sum().sort_values(by = "item_price",ascending = False).head()

      revenue
0        2.39
1        3.39
2        3.39
3        2.39
4       33.96
...       ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75

[4622 rows x 1 columns]

item_name
Chicken Bowl           8044.63
Chicken Burrito        6387.06
Steak Burrito          4236.13
Steak Bowl             2479.81
Chips and Guacamole    2475.62
Name: revenue, dtype: float64

# Chapter 3 - Pandas Data Structure

* 1D - Series
* 2D - DataFrame

In [143]:
pd.Series(data = [0, 2, 5.6])

0    0.0
1    2.0
2    5.6
dtype: float64

In [146]:
pd.DataFrame(data = {"name" : ["Kishore", "Sowmiya"]})

      name
0  Kishore
1  Sowmiya

In [ ]:
## Task
1. create a meaningful series
2. create a meaningful dataset using pandas dataframe with dict 5 observation across 6 features

# Chapter 4 - Filtering & Selection & Sorting

In [162]:
football_2012_data = pd.read_csv("Euro_2012_stats_TEAM.csv")
football_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [163]:
football_2012_data.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='str')

In [165]:
pd.set_option('display.max_rows', None)
football_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0,9,9,18

In [168]:
filete_euro_data = football_2012_data[["Team", "Goals", "Yellow Cards", "Red Cards"]]
filete_euro_data

                   Team  Goals  Yellow Cards  Red Cards
0               Croatia      4             9          0
1        Czech Republic      4             7          0
2               Denmark      4             4          0
3               England      5             5          0
4                France      3             6          0
5               Germany     10             4          0
6                Greece      5             9          1
7                 Italy      6            16          0
8           Netherlands      2             5          0
9                Poland      2             7          1
10             Portugal      6            12          0
11  Republic of Ireland      1             6          1
12               Russia      5             6          0
13                Spain     12            11          0
14               Sweden      5             7          0
15              Ukraine      2             5          0

In [170]:
filete_euro_data["Yellow Cards"].sort_values()

0      9
1      7
2      4
3      5
4      6
5      4
6      9
7     16
8      5
9      7
10    12
11     6
12     6
13    11
14     7
15     5
Name: Yellow Cards, dtype: int64

In [174]:
filete_euro_data.sort_values("Yellow Cards", ascending = False)

                   Team  Goals  Yellow Cards  Red Cards
7                 Italy      6            16          0
10             Portugal      6            12          0
13                Spain     12            11          0
0               Croatia      4             9          0
6                Greece      5             9          1
14               Sweden      5             7          0
9                Poland      2             7          1
1        Czech Republic      4             7          0
12               Russia      5             6          0
11  Republic of Ireland      1             6          1
4                France      3             6          0
3               England      5             5          0
8           Netherlands      2             5          0
15              Ukraine      2             5          0
5               Germany     10             4          0
2               Denmark      4             4          0

## 4.2 List the team which has got Red Cards

In [176]:
filete_euro_data["Red Cards"] == 1

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14    False
15    False
Name: Red Cards, dtype: bool

In [177]:
filete_euro_data[filete_euro_data["Red Cards"] == 1]

                   Team  Goals  Yellow Cards  Red Cards
6                Greece      5             9          1
9                Poland      2             7          1
11  Republic of Ireland      1             6          1

## 4.3 List the team which has gets more that 8 Yello Cards

In [179]:
filete_euro_data[filete_euro_data["Yellow Cards"] > 8]

        Team  Goals  Yellow Cards  Red Cards
0    Croatia      4             9          0
6     Greece      5             9          1
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0

## Task

1. Find out 5 new quesitions along with script answer

# Level 1

## Chapter 5 - How to deal with missing values

In [34]:
import pandas as pd

employee_data = pd.read_excel("employee_data.xlsx")
print(employee_data)

      Name   Age Department   Salary            Join_Date
0   Rajesh  29.0        Ops  60000.0           21-05-2023
1    Nasir  31.0    IT Tech      NaN  2020-12-11 00:00:00
2  Mathiew   NaN    Support  58000.0           15-01-2025
3  Gilbert  29.0        Ops  60000.0           21-05-2021
4    Kevin  28.0    Support  61000.0           30-07-2024
5    Navin  35.0    Support  72000.0           19-08-2023
6      NaN  40.0         IT  64000.0  2022-10-09 00:00:00
7    Nasir  31.0    IT Tech      NaN  2020-12-11 00:00:00

## Step 1: i will call to my client, and check with his if he can give the rigth data

Incase client asking us to perform the data cleaning operation

In [35]:
employee_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        2
Join_Date     0
dtype: int64

In [36]:
employee_data.dtypes

Name              str
Age           float64
Department        str
Salary        float64
Join_Date      object
dtype: object

In [37]:
employee_data.describe(include="all")

         Name        Age Department        Salary            Join_Date
count       7   7.000000          8      6.000000                    8
unique      6        NaN          4           NaN                    7
top     Nasir        NaN    Support           NaN  2020-12-11 00:00:00
freq        2        NaN          3           NaN                    2
mean      NaN  31.857143        NaN  62500.000000                  NaN
std       NaN   4.259443        NaN   5049.752469                  NaN
min       NaN  28.000000        NaN  58000.000000                  NaN
25%       NaN  29.000000        NaN  60000.000000                  NaN
50%       NaN  31.000000        NaN  60500.000000                  NaN
75%       NaN  33.000000        NaN  63250.000000                  NaN
max       NaN  40.000000        NaN  72000.000000                  NaN

In [38]:
employee_data.shape

(8, 5)

In [39]:
employee_data.drop_duplicates(inplace= True)
employee_data

      Name   Age Department   Salary            Join_Date
0   Rajesh  29.0        Ops  60000.0           21-05-2023
1    Nasir  31.0    IT Tech      NaN  2020-12-11 00:00:00
2  Mathiew   NaN    Support  58000.0           15-01-2025
3  Gilbert  29.0        Ops  60000.0           21-05-2021
4    Kevin  28.0    Support  61000.0           30-07-2024
5    Navin  35.0    Support  72000.0           19-08-2023
6      NaN  40.0         IT  64000.0  2022-10-09 00:00:00

In [40]:
# After duplicate removers

employee_data.shape

(7, 5)

In [44]:
employee_data.dropna(inplace = True)
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [45]:
employee_data.shape

(4, 5)

#### step 3 :Record in a docuement

The client gave a total of 7 observations or records with 5 parameters and 7 out of which 3 entries are removed because those records 
Don't have complete information

#### Step 4 Get Approval
* Send this to client and get approval to proceed for model building or model training

In [46]:
employee_data.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

# Level 2 Data Cleaning

In [57]:
import pandas as pd

employee_added_details =  pd.read_excel("employee_data.xlsx" , sheet_name = "More Employee")
employee_added_details

             Name Age Department Salary            Join_Date
0          Rajesh  29        Ops  60000          21-05-2023
1           Nasir  31    IT Tech  62000  2020-12-11 00:00:00
2         Mathiew   —    Support  58000          15-01-2025
3         Gilbert  29        Ops  60000          21-05-2021
4           Kevin  28    Support  61000          30-07-2024
5           Navin  35    Support  72000          19-08-2023
6               —  40    IT Tech  64000  2022-10-09 00:00:00
7          Roshan  31    IT Tech      —  2020-12-11 00:00:00
8       Kuppusamy  28        Ops      —          21-05-2021
9           Ajesh  28    Support      —          30-07-2024
10           Diya  31    IT Tech  63000  2020-12-11 00:00:00
11        Mathiew   —    Support  58000          15-01-2025
12  Jagadheeswari  28    IT Tech      —                   —
13           Mani  28        Ops      —          21-05-2021

In [60]:
employee_added_details.shape

(14, 5)

#### Step 1: Drop Duplicates

In [61]:
employee_added_details.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
dtype: bool

In [64]:
employee_added_details.drop_duplicates(inplace=True)
employee_added_details

             Name Age Department Salary            Join_Date
0          Rajesh  29        Ops  60000          21-05-2023
1           Nasir  31    IT Tech  62000  2020-12-11 00:00:00
2         Mathiew   —    Support  58000          15-01-2025
3         Gilbert  29        Ops  60000          21-05-2021
4           Kevin  28    Support  61000          30-07-2024
5           Navin  35    Support  72000          19-08-2023
6               —  40    IT Tech  64000  2022-10-09 00:00:00
7          Roshan  31    IT Tech      —  2020-12-11 00:00:00
8       Kuppusamy  28        Ops      —          21-05-2021
9           Ajesh  28    Support      —          30-07-2024
10           Diya  31    IT Tech  63000  2020-12-11 00:00:00
12  Jagadheeswari  28    IT Tech      —                   —
13           Mani  28        Ops      —          21-05-2021

#### Step 2 Identify null Entries

In [69]:
import numpy as np

employee_added_details.replace("—", np.nan, inplace= True)
employee_added_details.isnull().sum()

Name          1
Age           1
Department    0
Salary        5
Join_Date     0
dtype: int64

#### Step 3 : Go for best Imputation

In [72]:
employee_added_details["Department"].unique()

<StringArray>
['Ops', 'IT Tech', 'Support']
Length: 3, dtype: str

In [73]:
employee_added_details["Department"] == "Support"

0     False
1     False
2      True
3     False
4      True
5      True
6     False
7     False
8     False
9      True
10    False
12    False
13    False
Name: Department, dtype: bool

In [74]:
employee_added_details[employee_added_details["Department"] == "Support"]

      Name  Age Department Salary    Join_Date
2  Mathiew  NaN    Support  58000  15-01-2025
4    Kevin   28    Support  61000  30-07-2024
5    Navin   35    Support  72000  19-08-2023
9    Ajesh   28    Support    NaN  30-07-2024

In [76]:
employee_added_details[employee_added_details["Department"] == "IT Tech"]

             Name Age Department Salary            Join_Date
1           Nasir  31    IT Tech  62000  2020-12-11 00:00:00
6             NaN  40    IT Tech  64000  2022-10-09 00:00:00
7          Roshan  31    IT Tech    NaN  2020-12-11 00:00:00
10           Diya  31    IT Tech  63000  2020-12-11 00:00:00
12  Jagadheeswari  28    IT Tech    NaN                   —

In [78]:
employee_added_details[employee_added_details["Department"] == "Ops"]

         Name Age Department Salary    Join_Date
0      Rajesh  29        Ops  60000  21-05-2023
3     Gilbert  29        Ops  60000  21-05-2021
8   Kuppusamy  28        Ops    NaN  21-05-2021
13       Mani  28        Ops    NaN  21-05-2021

### Data Analytics Task
1. Impute The relevant value in the salary column wherever it is Nan, based on department
2. Impute Mathew's age as 27

In [79]:
employee_added_details[employee_added_details["Department"] == "Support"]

      Name  Age Department Salary    Join_Date
2  Mathiew  NaN    Support  58000  15-01-2025
4    Kevin   28    Support  61000  30-07-2024
5    Navin   35    Support  72000  19-08-2023
9    Ajesh   28    Support    NaN  30-07-2024

In [92]:
employee_added_details[(employee_added_details["Department"] == "Support") & (employee_added_details["Salary"].isna())]

    Name Age Department Salary    Join_Date
9  Ajesh  28    Support    NaN  30-07-2024

In [98]:
employee_added_details[(employee_added_details["Department"] == "Support") & (employee_added_details["Salary"].isna())]
employee_added_details.loc[(employee_added_details["Department"] == "Support") & (employee_added_details["Salary"].isna()),"Salary"] = 61000

employee_added_details

             Name  Age Department Salary            Join_Date
0          Rajesh   29        Ops  60000          21-05-2023
1           Nasir   31    IT Tech  62000  2020-12-11 00:00:00
2         Mathiew  NaN    Support  58000          15-01-2025
3         Gilbert   29        Ops  60000          21-05-2021
4           Kevin   28    Support  61000          30-07-2024
5           Navin   35    Support  72000          19-08-2023
6             NaN   40    IT Tech  64000  2022-10-09 00:00:00
7          Roshan   31    IT Tech    NaN  2020-12-11 00:00:00
8       Kuppusamy   28        Ops    NaN          21-05-2021
9           Ajesh   28    Support  61000          30-07-2024
10           Diya   31    IT Tech  63000  2020-12-11 00:00:00
12  Jagadheeswari   28    IT Tech    NaN                   —
13           Mani   28        Ops    NaN          21-05-2021