# Scripting Based Questions

#### 1.Write a program to take a name and age from the user and print a greeting message.

In [ ]:


user_name = input("Enter Your Name").strip()
user_age = input("Enter your Age").strip()
if not user_name:
    print("Name cannot be empty.")
elif not user_age:
    print("Age cannot be empty.")
elif not user_age.isdigit():
    print("Please enter a valid age.")
else:
    print("Welcome to Python Programming.")

#### 2.Create a list of numbers and print only even numbers using a for loop.

In [13]:
list_of_number = [2,4,5,7,10,15,6]
even_list = []
for i in list_of_number:
    if i%2==0:
        even_list.append(i)
print("This is an even numbers = ", even_list)

This is an even numbers =  [2, 4, 10, 6]

#### 3.Write a program that handles division by zero using try-except.

In [31]:
try:
    user1_input = input("Enter a number")
    user2_input = input("Enter a number")
    if not user1_input or not user2_input:
        print("Please enter a number")
    elif not user1_input.isdigit() or not user2_input.isdigit():
        print("Please enter a valid number")
    else:
        result = int(user1_input)/int(user2_input)
        print("Result is", result)
except Exception as e:
    print("Cannot divide by zero", e)

Result is 0.0

#### 4.Given a string, count how many vowels it has.

In [36]:
user_name = input("Enter Your Name").strip()
vowels = "aeiouAEIOU"
count = 0
for i in user_name:
    if i in vowels:
        print(i, end=" ")
        count +=1
print("\nTotal number of vowels: ", count)

i i e
Total number of vowels:  3

#### 5. Reverse a list without using built-in functions.

In [3]:
original_list = [1,2,3,4,5,6,7,8,9]
reverse_list = []
for i in original_list:
    reverse_list.insert(0, i)
print(reverse_list)


original_str_list = ["Apple", "Mango", "Banana"]
reverse_str_list = []
for i in original_str_list:
    reverse_str_list.insert(0, i)
print(reverse_str_list)

[9, 8, 7, 6, 5, 4, 3, 2, 1]
['Banana', 'Mango', 'Apple']

#### 6.Create a dictionary with at least 5 key-value pairs and print them.

In [4]:

student_list = {
    "name": "Ram",
    "age": 20,
    "grade": "A",
    "course": "Computer Science",
    "city": "Chennai"
}

print(student_list)

{'name': 'Ram', 'age': 20, 'grade': 'A', 'course': 'Computer Science', 'city': 'Chennai'}

#### 7.Write a Pandas code to read a CSV and print the top 5 rows.

In [5]:
import pandas as pd

employee_details = pd.read_csv(r"C:\Users\Kisho\Downloads\tamilnadu_employee_data.csv")

In [6]:
employee_details.shape

(22, 5)

In [7]:
employee_details.isnull().sum()

Name          0
Age           0
Department    1
City          1
Salary        2
dtype: int64

In [8]:
employee_details.describe(include="all")

              Name        Age Department     City        Salary
count           22  22.000000         21       21     20.000000
unique          20        NaN          7       19           NaN
top     Arun Kumar        NaN         IT  Chennai           NaN
freq             2        NaN          5        2           NaN
mean           NaN  30.409091        NaN      NaN  56850.000000
std            NaN   5.039455        NaN      NaN  10979.766079
min            NaN  23.000000        NaN      NaN  39000.000000
25%            NaN  27.000000        NaN      NaN  48000.000000
50%            NaN  29.000000        NaN      NaN  55000.000000
75%            NaN  33.750000        NaN      NaN  66500.000000
max            NaN  41.000000        NaN      NaN  75000.000000

In [9]:
employee_details.drop_duplicates()

          Name  Age  Department             City   Salary
0   Arun Kumar   25          IT          Chennai  55000.0
1      Priya S   29          HR       Coimbatore  48000.0
2    Karthik R   31     Finance          Madurai  62000.0
3      Divya M   27       Sales            Salem      NaN
4    Vignesh P   35   Marketing  Tiruchirappalli  70000.0
5      Nisha K   24          IT              NaN  45000.0
6     Suresh B   38  Operations            Erode  68000.0
7    Lakshmi T   30          HR          Vellore  52000.0
8      Manoj C   26     Support      Thoothukudi  40000.0
9    Keerthi A   28     Finance        Thanjavur      NaN
10      Ravi N   33          IT         Dindigul  61000.0
11    Anitha G   29       Sales            Karur  50000.0
12   Prakash V   41         NaN         Namakkal  75000.0
13     Meena R   32   Marketing      Kanchipuram  66000.0
14      Hari S   27          IT        Cuddalore  47000.0
15     Deepa L   36          HR         Sivakasi  64000.0
16     Gokul M   23     Support     Nagapattinam  39000.0
17   Saranya P   34     Finance            Hosur  69000.0
18   Senthil K   39  Operations        Nagercoil  72000.0
19    Yamini D   28       Sales         Pollachi  51000.0

In [10]:
employee_details.dropna()

          Name  Age  Department             City   Salary
0   Arun Kumar   25          IT          Chennai  55000.0
1      Priya S   29          HR       Coimbatore  48000.0
2    Karthik R   31     Finance          Madurai  62000.0
4    Vignesh P   35   Marketing  Tiruchirappalli  70000.0
6     Suresh B   38  Operations            Erode  68000.0
7    Lakshmi T   30          HR          Vellore  52000.0
8      Manoj C   26     Support      Thoothukudi  40000.0
10      Ravi N   33          IT         Dindigul  61000.0
11    Anitha G   29       Sales            Karur  50000.0
13     Meena R   32   Marketing      Kanchipuram  66000.0
14      Hari S   27          IT        Cuddalore  47000.0
15     Deepa L   36          HR         Sivakasi  64000.0
16     Gokul M   23     Support     Nagapattinam  39000.0
17   Saranya P   34     Finance            Hosur  69000.0
18   Senthil K   39  Operations        Nagercoil  72000.0
19    Yamini D   28       Sales         Pollachi  51000.0
20  Arun Kumar   25          IT          Chennai  55000.0
21     Priya S   29          HR       Coimbatore  48000.0

In [20]:
employee_details.groupby("Department")["Salary"].max().head()

Department
Finance       69000.0
HR            64000.0
IT            61000.0
Marketing     70000.0
Operations    72000.0
Name: Salary, dtype: float64

#### 8.Create a DataFrame from a Python dictionary.

In [21]:
import pandas as pd


employee_data = {
    "Name": ["Arun", "Priya", "Karthik", "Divya", "Vignesh"],
    "Age": [25, 29, 31, 27, 35],
    "Department": ["IT", "HR", "Finance", "Sales", "Marketing"],
    "Salary": [55000, 48000, 62000, 50000, 70000]
}


employee_details = pd.DataFrame(employee_data)

print(employee_details)

      Name  Age Department  Salary
0     Arun   25         IT   55000
1    Priya   29         HR   48000
2  Karthik   31    Finance   62000
3    Divya   27      Sales   50000
4  Vignesh   35  Marketing   70000

#### 9. Replace all missing values in a DataFrame with the column’s mean.

In [16]:
import pandas as pd
emp_details = pd.read_csv((r"C:\Users\Kisho\Downloads\tamilnadu_employee_data.csv"))
emp_details["Salary"]
emp_details["Salary"] = emp_details["Salary"].fillna(value = emp_details["Salary"].mean())
emp_details

          Name  Age  Department             City   Salary
0   Arun Kumar   25          IT          Chennai  55000.0
1      Priya S   29          HR       Coimbatore  48000.0
2    Karthik R   31     Finance          Madurai  62000.0
3      Divya M   27       Sales            Salem  56850.0
4    Vignesh P   35   Marketing  Tiruchirappalli  70000.0
5      Nisha K   24          IT              NaN  45000.0
6     Suresh B   38  Operations            Erode  68000.0
7    Lakshmi T   30          HR          Vellore  52000.0
8      Manoj C   26     Support      Thoothukudi  40000.0
9    Keerthi A   28     Finance        Thanjavur  56850.0
10      Ravi N   33          IT         Dindigul  61000.0
11    Anitha G   29       Sales            Karur  50000.0
12   Prakash V   41         NaN         Namakkal  75000.0
13     Meena R   32   Marketing      Kanchipuram  66000.0
14      Hari S   27          IT        Cuddalore  47000.0
15     Deepa L   36          HR         Sivakasi  64000.0
16     Gokul M   23     Support     Nagapattinam  39000.0
17   Saranya P   34     Finance            Hosur  69000.0
18   Senthil K   39  Operations        Nagercoil  72000.0
19    Yamini D   28       Sales         Pollachi  51000.0
20  Arun Kumar   25          IT          Chennai  55000.0
21     Priya S   29          HR       Coimbatore  48000.0

#### 10.Filter rows in a DataFrame where the "Age" column is greater than 30.[Text Wrapping Break]

In [25]:
import pandas as pd
employee_details = pd.read_csv(r"C:\Users\Kisho\Downloads\tamilnadu_employee_data.csv")
employee_details.drop_duplicates()
employee_details.dropna()
employee_details[employee_details["Age"]>30]

         Name  Age  Department             City   Salary
2   Karthik R   31     Finance          Madurai  62000.0
4   Vignesh P   35   Marketing  Tiruchirappalli  70000.0
6    Suresh B   38  Operations            Erode  68000.0
10     Ravi N   33          IT         Dindigul  61000.0
12  Prakash V   41         NaN         Namakkal  75000.0
13    Meena R   32   Marketing      Kanchipuram  66000.0
15    Deepa L   36          HR         Sivakasi  64000.0
17  Saranya P   34     Finance            Hosur  69000.0
18  Senthil K   39  Operations        Nagercoil  72000.0